---
apiVersion: v1
kind: Namespace
metadata:
  name: go-echo-project
  labels:
    env: development
    team: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
  namespace: go-echo-project
  labels:
    app: go-echo
    team: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: quay.io/lagomes/go-echo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-nodeport
  namespace: go-echo-project
  labels:
    app: go-echo
spec:
  type: NodePort
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007